# permissions for end users to edit beverages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beverage-editor-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - beverages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - beverages/status
  verbs:
  - get
